# Generated by Django 5.0.4 on 2024-05-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='avion',
            name='avion_origen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avion.aeropuerto'),
        ),
    ]
