# Generated by Django 5.0.6 on 2024-05-18 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avion', '0002_aeropuerto_avion_avion_origen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='pais_origen',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
