# Generated by Django 5.0.6 on 2024-05-22 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avion', '0003_aeropuerto_pais_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='avion',
            name='capacidad_maxima',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avion',
            name='fecha_incorporacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
