# Generated by Django 5.0.6 on 2024-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avion', '0006_remove_usuario_nombre_usuario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='nombre por defecto', max_length=40),
        ),
    ]
